#!/bin/bash
packages=(
  alacritty
  bin
  btop
  ghostty
  git
  lazygit
  starship
  taskwarrior
  tms
  tmux
  zsh
)

for package in "${packages[@]}"; do
  stow -R -v -t ~ -d ~/dotfiles "$package"
done
