#!/bin/bash
packages=(
  bin
  btop
  ghostty
  git
  lazygit
  starship
  taskwarrior
  tmux
  zsh
)

for package in "${packages[@]}"; do
  stow -R -v -t ~ -d ~/dotfiles "$package"
done

# Special case for nvim (submodule) - direct symlink
if [ ! -L ~/.config/nvim ]; then
  ln -sfn ~/dotfiles/nvim ~/.config/nvim
  echo "LINK: nvim -> ~/dotfiles/nvim"
fi
