gui:
 scrollHeight: 7
 # mocha catppuccin
 theme:
   activeBorderColor:
     - '#89b4fa'
     - bold
   inactiveBorderColor:
     - '#a6adc8'
   optionsTextColor:
     - '#89b4fa'
   selectedLineBgColor:
     - '#313244'
   cherryPickedCommitBgColor:
     - '#45475a'
   cherryPickedCommitFgColor:
     - '#89b4fa'
   unstagedChangesColor:
     - '#f38ba8'
   defaultFgColor:
     - '#cdd6f4'
   searchingActiveBorderColor:
     - '#f9e2af'

git:
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
  paging:
    pager: "delta --dark --paging=never"

nerdFontsVersion: 3
